---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  default.conf: |
    server {
      listen       8080;
      server_name  localhost;
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
      - name: config
        mountPath: "/etc/nginx/conf.d"
  volumes:
  - name: config
    configMap:
      name: my-configmap
