{{- if .Values.volumes -}}
{{- range $vol := $.Values.volumes }}
apiVersion: v1
data:
  index.html: |
    <html>
    <h1>Andrew Savelyev</h1>
    <body>
    This is My Nginx Server with name {{ .name | quote }}
    Last Release
    </body>
    </html>
kind: ConfigMap
metadata:
  name: {{ .name }}
{{- end }}
{{- end }}
